### ISSUE TITLE
✨ [Feature] 전체일정 추가 API 작성

### ISSUE THREAD

**Issue by wonies** [42organization/42gg.server.dev.v2#1052]
### Description

- 전체일정 추가 API 작성

### Todo

- [x] 추가 Request DTO 작성
- [ ] 추가 Response DTO 작성
- [x] Service 작성
- [x] Controller 작성
- [ ] Test code 작성
