### ISSUE TITLE
🧪 [Test] 테스팅 환경 구축

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#333]
### Description

테스트 환경이 로컬 DB에 종속되어 있고
Flyway 가 alter table 명령어부터 시작하는 관계로 해당 파일로 테스팅 환경 생성이 어려워
현재는 단위 테스팅이 어려운 상황입니다.
테스트를 할 수 있도록 테스팅 환경을 구축 합니다.

### Todo

- [x] Test용 schema.sql 파일 생성
- [x] TestContainers 생성
- [x] Test용 yml 파일 생성
- [x] 테스트 S3 처리
- [x] 테스트 Oauth 처리
