### ISSUE TITLE
🔨 [Refactoring] main merge 전 dev 브랜치 수정사항

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#372]
### Description

- main merge 전 dev 브랜치 코드 리뷰 수정하기

### Todo
- [ ] [custom exception 기본 생성자로 전체 수정](https://github.com/42organization/42gg.server.dev.v2/pull/368#discussion_r1422323582)
- [ ] [synchronized 삭제](https://github.com/42organization/42gg.server.dev.v2/pull/368#discussion_r1422327899)
- [ ] [GameRepository return type에 Optional 추가](https://github.com/42organization/42gg.server.dev.v2/pull/368#discussion_r1422330002)
- [ ] [GameRepository 공백추가](https://github.com/42organization/42gg.server.dev.v2/pull/368#discussion_r1422334035)
- [ ] [Tournament Entity에 ToString annotation 삭제](https://github.com/42organization/42gg.server.dev.v2/pull/368#discussion_r1422345804)
