### ISSUE TITLE
✨ [Feature] 테스트 환경 개선 및 CI 추가

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#374]
### Description
더 안정적인 개발 환경을 위해 테스팅 환경을 다양화하고, pull request 진행할 때 테스트 ci를 추가합니다.

### Todo
- [x] 코드 커버리지 측정도구 추가
- [ ] unit, integration 테스트 분리
- [ ] redis testContainer 추가
- [ ] 테스트 git action 추가
