### ISSUE TITLE
✨ [Feature] 토너먼트 연관관계 메서드 처리

### ISSUE THREAD

**Issue by middlefitting** [42organization/42gg.server.dev.v2#378]
### Description

tournament game, tournamet user entity에 연관관계 메서드를 추가합니다.

### Todo

- [x] tournament 연관관계 메서드 처리
- [x] tournament game 연관관계 메서드 처리
- [x]  tournamet user 연관관계 메서드 처리
