### ISSUE TITLE
✨ [Feature] 5기 문서화 작업

### ISSUE THREAD

**Issue by Kimhan-nah** [42organization/42gg.server.dev.v2#460]
### Description

- 5기 활동 문서화 작업

### Todo

- [ ] README 업데이트
- [ ] 인수인계에 필요한 내용 문서화
  - [x] 서버 마이그레이션
  - [x] CI/CD 
  - [x] 테스트코드
  - [ ] flyway 설명 추가
- [ ] 온보딩 자료 업데이트
