### ISSUE TITLE
🔨 [Refactoring] Agenda 리펙토링

### ISSUE THREAD

**Issue by yhames** [42organization/42gg.server.dev.v2#925]
### Description

Agenda에 관련된 API 및 엔티티를 리펙토링 합니다.

### Todo

- [ ] Agenda 종료 및 시상하기 기능
  - [ ] finishAgendaWithAwards() 메서드 분리
  - [ ] confirmAgenda() N+1 문제 해결
- [ ] Agenda 엔티티 코드 정리
  - [ ] 메서드 순서 정리 및 중복 제거
