### ISSUE TITLE
🔨 [Refactoring] 진행중 대회 전체조회 API 분리

### ISSUE THREAD

**Issue by yhames** [42organization/42gg.server.dev.v2#992]
### Description

🔨 [Refactoring] 진행중 대회 전체조회 API 분리

### Todo

- [x] 모집중인 대회 조회 GET /agenda/open
- [x] 진행중인 대회 조회 GET /agenda/confirm
  - [x] GET /agenda/list -> GET /agenda/confirm
